project:
  type: book

book:
  title: "ML Notes"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/ml-notes
  site-url: https://ml-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: Model Explainability
      chapters: 
        - "content/explain/shap-01-intro.qmd"

bibliography: references.bib

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    toc-depth: 4
    code-fold: show

execute: 
  freeze: auto